# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Bambinotes PreK
email: contacto@bambinotes.com
description: > # this means to ignore newlines until "baseurl:"
  La nueva libreta de comunicaciones virtual para jardines, escuelas y centros preescolares.
  Comunícate de manera instantánea y privada con los apoderados del jardín, kinder, after school o escuela de lenguaje.
baseurl: "/bambinotes-prek" # the subpath of your site, e.g. /blog
url: "http://www.bambinotes.com" # the base hostname & protocol for your site
twitter_username: bambinotes_prek

# Build settings
markdown: kramdown
author:
  name: Bambinotes
